import type { Metadata } from "next";
import "./globals.css";

// next/font/google is intentionally NOT used. In dev mode it fetches
// the font CSS from fonts.googleapis.com at request time, which hangs
// forever inside this container (no internet access, and the configured
// proxy at 127.0.0.1:7897 is not running). That hung request blocks the
// page render and makes /embed/auth (the SSR target of /api/embed/auth)
// never respond. globals.css already declares a system font stack as
// the primary font-family, so removing the Geist CSS variables is safe.

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
